#include<stdio.h>
#include<string.h>
#define SIZE 100
#define BASE 10

// addition function
void add(char*arr1,char*arr2)
{
    int carry=0;
    char arr3[SIZE+1];
    for(int i=SIZE-1;i>=0;i--)
    {
        arr3[i+1]=(arr1[i]+arr2[i]-2*'0'+carry)%BASE+'0';
        carry=(arr1[i]+arr2[i]-2*'0'+carry)/BASE;
    }
    for(int i=0;i<=SIZE;i++)
    printf("%c",arr3[i]);
}

//substraction function using 2's complement
void subtract(char*arr1,char*arr2)
{
    int carry;
    char arr3[SIZE+1]; //for null character
    carry=1;
    arr3[0]='0';
    for(int i=SIZE-1;i>=0;i--)
    {
        arr3[i+1]=(arr1[i]-'0' + (9 -(arr2[i]-'0'))+carry)%BASE+'0';
        carry=(arr1[i]+9-(arr2[i]-'0')-'0'+carry)/BASE;
    }
    if(carry==0) // means number is negative (in 2's complement method, if carry does not come then the number is -ve)
    {
        carry=1;
        printf("-");
        for(int i=SIZE-1;i>=0;i--)
        {
            arr3[i+1]=(9-(arr3[i+1]-'0')+carry)%BASE+'0';
            carry=(9-arr3[i+1]+'0'+carry)/BASE;
        }
        arr3[0]='0';
    } // the answer in this case is 2's complement itself
    for(int i=0;i<=SIZE;i++)printf("%c",arr3[i]); // printing 2's complement, which is the answer
}

//multiplication function
void multiply(char*arr1,char*arr2)
{
    char arr3[2*SIZE];
    for(int i=0;i<2*SIZE;i++)
        arr3[i]='0'; // filling out zeroes in arr3(result storing array)
    for(int i=strlen(arr2)-1;i>=0;i--) // outer loop to multiply number digit by digit   
    {
        int carry=0;
        char temp[2*SIZE]; // third temporary array is made to store the digit wise multiplication number 
        for(int l=0;l<2*SIZE;l++)temp[l]='0';

        // multiplying two numbers as we do mathematically and incrementing the decimal value
        for(int j=strlen(arr1)-1;j>=0;j--) //inner loop to add the obtained numbers using into result array arr3 
        {
            temp[2*SIZE-(strlen(arr1)-j)-(strlen(arr2)-i)+1]=((arr2[i]-'0')*(arr1[j]-'0')+carry)%BASE+'0';
            carry=((arr2[i]-'0')*(arr1[j]-'0')+carry)/BASE;
        }

        // to handle the last carry at the end of all multiplication
        temp[2*SIZE-strlen(arr1)+i-strlen(arr2)]=carry+'0';
        carry=0;

        //loop for addition the upcoming numbers generated by multiplying 
        for(int k=2*SIZE-1;k>=0;k--)
        {
            char t=arr3[k];
            arr3[k]=(arr3[k]-'0'+temp[k]-'0'+carry)%BASE+'0';
            carry=(t+temp[k]-2*'0'+carry)/BASE;
        }
    }

    // printing the final number 
    for(int i1=0;i1<2*SIZE;i1++)printf("%c",arr3[i1]);
}

// set the length of number to 'SIZE' to suit the algorithm input conditions
void setno(char*num)
{
    if(strlen(num)<SIZE)
    {
        char temp[SIZE+1];
        temp[0]='\0';
        for(int i=0;i<SIZE-strlen(num);i++)
        {
            char ch[2]={'0','\0'};
            strcat(temp,ch);
        }
        strcat(temp,num);
        strcpy(num,temp);
    }
}

int main()
{
    char arr1[SIZE+1],arr2[SIZE+1];
    int carry=0;
    printf("enter the first BigInt number: ");
    scanf("%s",arr1);
    printf("enter the first BigInt number: ");
    scanf("%s",arr2);
    setno(arr1);
    setno(arr2);

    add(arr1,arr2);
    printf("\n");

    subtract(arr1,arr2);
    printf("\n");
    
    multiply(arr1, arr2);

    return 0;
}